# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "v4l2loopback" "amdgpu" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.v4l2loopback
  ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/2b7b36ca-3879-4c2b-9d3e-d5d4c88ca913";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b17adae4-357e-4cc7-be84-c0f52d60cca6".device = "/dev/disk/by-uuid/b17adae4-357e-4cc7-be84-c0f52d60cca6";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/73D7-7370";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e664d1e3-a166-409c-bd05-bcdda69b3ce3"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
