#!/usr/bin/env bash

input_base="$(git rev-parse --show-toplevel)/secrets"
output_base="$HOME/.config/secrets"

yubikey_identities="$(mktemp)"
age-plugin-yubikey --identity > "$yubikey_identities"

mkdir -p "$output_base"
chmod 700 "$output_base"

activate-secret(){
    input="$input_base/$1.age"
    output="$output_base/$1"

    rm -f "$output"
    rage --decrypt -i "$yubikey_identities" -o "$output" "$input"
    chmod 400 "$output"
}

activate-secret buildkite_api_key
activate-secret jupyter_token
activate-secret github_token

rm "$yubikey_identities"
